import random
import os

from coordinator import Checker, Reformer, Coordinator

from agents import Agent, function_tool

MODEL = (os.getenv("MODEL") or "o3-mini").strip() or "o3-mini"

coordinator_function = None

class CoordinatorManager(Agent):
    instructions="""You are the head of a network of LLM Agents. Your job is to take a request for a series of worlds to generate, and correspondingly prompt the Coordinator agent by calling run_coordinator. Each stage suggested by YOUR prompt should be a seperate world, each generated by a seperate Coordinator."""

    def __init__(self, run_coordinator_function, name=None, instructions=None, ):
        global coordinator_function
        coordinator_function  = run_coordinator_function
        super().__init__(
            name=name or f"CoordinatorManager{random.randint(100,999)}",
            instructions=instructions or CoordinatorManager.instructions,
            tools=[run_coordinator],
            model=MODEL,
        )

@function_tool
async def run_coordinator(coordinator_prompt: str, name_for_this_coordinator: str) -> str:
    """
        Prompts a Coordinator agent to generate a world according to the prompt. Keep the prompt to-the-point, minimal, and clear. Only refer to a single world, with no mention of stages.
        coordinator_prompt: the prompt that you give to the coordinator for this world. Example: Generate a small world that only contains a fish tank with a clownfish in it.
        name_for_this_coordinator: just a name for this coordinator for reference. Example: Small-building world coordinator
    """
    print(f"{name_for_this_coordinator} called")
    await coordinator_function(coordinator_prompt)
    print(f"{name_for_this_coordinator} done")
